server:
  port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/saga-sales
    username: postgres
    password: postgres

  database:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
